services:
  - type: web
    name: webTFG
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    rootDir: backend

  - type: static
    name: webTFG-frontend
    buildCommand: ""
    staticPublishPath: .
    rootDir: frontend
